### ISSUE TITLE
Initial Setup Issue

### ISSUE THREAD

**Issue by gatlingrisso** [AnesHamdani08/AniLife#1]
Using the latest release when I launch the program I'm greeted with the initial setup page, I click the arrow, and then these two boxes pop up, I am not sure what to do here. Pressing OK or cancel seems to just cycle through the boxes again.
![image](https://user-images.githubusercontent.com/33464639/174017790-1c5c60aa-5ebf-452f-a3d3-db22b7f37ae7.png)
![image](https://user-images.githubusercontent.com/33464639/174017865-2e20164b-76fb-4341-966f-e559d04611dd.png)

**Comment by AnesHamdani08** [comment]
Sorry for not noticing your issue , but the client settings input boxes are : the client name , and the client version , you make an account at anidb , and then create a software [here](https://anidb.net/software/add). Click add new client at the top right , choose a name and a version and fill them in the app.

**Comment by ghost** [comment]
it has to be HTTP, by the way
